// <auto-generated />
using Allison.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Allison.Model.Migrations
{
    [DbContext(typeof(AllisonContext))]
    partial class AllisonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Allison.Model.MessageBubble", b =>
                {
                    b.Property<int>("MessageBubbleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LiveTime");

                    b.Property<string>("Message");

                    b.Property<bool>("News");

                    b.Property<string>("NewsImage");

                    b.Property<string>("NewsTime");

                    b.Property<string>("NewsTitle");

                    b.Property<string>("NewsUrl");

                    b.Property<bool>("Select");

                    b.Property<bool>("To");

                    b.Property<string>("VideoImage");

                    b.Property<string>("VideoTitle");

                    b.Property<string>("VideoUrl");

                    b.Property<bool>("Yo");

                    b.Property<bool>("Youtube");

                    b.HasKey("MessageBubbleId");

                    b.ToTable("MessageBubble");
                });
#pragma warning restore 612, 618
        }
    }
}
